### ISSUE TITLE
Readthedocs is failing

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#344]
Readthedocs fails:
```
/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/checkouts/latest/examples/03_data_features/007_comparative_assessment.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/checkouts/latest/examples/03_data_features/007_comparative_assessment.py", line 60, in <module>
    fp.plot(ax=axs[j, i])
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/checkouts/latest/siibra/features/tabular/receptor_density_fingerprint.py", line 160, in plot
    return super().plot(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/checkouts/latest/siibra/features/tabular/tabular.py", line 92, in plot
    ax = self.data.plot(kind="bar", **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_core.py", line 975, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py", line 451, in generate
    self._adorn_subplots()
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py", line 676, in _adorn_subplots
    handle_shared_axes(
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_matplotlib/tools.py", line 430, in handle_shared_axes
    if is_first_col(ax):
  File "/home/docs/checkouts/readthedocs.org/user_builds/siibra-python/envs/latest/lib/python3.8/site-packages/pandas/plotting/_matplotlib/tools.py", line 396, in <lambda>
    is_first_col = lambda x: x.get_subplotspec().is_first_col()
AttributeError: 'SubplotSpec' object has no attribute 'is_first_col'
```

As a result, the documentation is not up-to-date since [be60d114488194308e49691d54c5df3222b0fe69](https://github.com/FZJ-INM1-BDA/siibra-python/commit/be60d114488194308e49691d54c5df3222b0fe69)

**Comment by AhmetNSimsek** [comment]
46143466c5c472daf3ce31d065fa99bf85fce141 solves this issue
