### ISSUE TITLE
feature.export sometimes fails, when url is undefined

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#468]
as of 0.4a64

sample code:

```python
import siibra
re = siibra.get_region("2.9", "hoc1 left")
features = siibra.features.get(re, "ebrains")
feat = features[0]
feat.export("foo.zip")
```

expected:

zip to be written

actual:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xgui3783/dev/projects/siibra-api/venv/lib/python3.10/site-packages/siibra/features/feature.py", line 223, in export
    self._export(fh)
  File "/home/xgui3783/dev/projects/siibra-api/venv/lib/python3.10/site-packages/siibra/features/dataset/ebrains.py", line 90, in _export
    fh.writestr("doi.md", DOI_TMPL.format(self.url))
KeyError: 'doi'
```

**Comment by AhmetNSimsek** [comment]
Fixed as of c2c25aacfcadcc3765f8cb08529e45553bda0872. Please reopen if it persists in another way.
