### ISSUE TITLE
[bug][0.4] siibra Space.get_template().fetch(voi=BoundingBox) raises HTTP Error

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#604]
sample code

siibra-python version: `0.4a80`

```python
sp = siibra.spaces["big brain"]
bbox = sp.get_bounding_box((-54.90,-29.47,12.66), (12.69,38.12,80.24))
nii = sp.get_template().fetch(voi=bbox, resolution_mm=0.52)
```

expected result:

gets nifti at the requested resolution

actual result:

```
Traceback (most recent call last):
  File "/home/xiao/tmp/siibra-python/venv/lib/python3.10/site-packages/neuroglancer_scripts/http_accessor.py", line 72, in fetch_file
    r.raise_for_status()
  File "/home/xiao/tmp/siibra-python/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://neuroglancer.humanbrainproject.eu/precomputed/BigBrainRelease.2015/8bit/320um/0-64_64-128_384-357

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiao/tmp/siibra-python/foo.py", line 30, in <module>
    err()
  File "/home/xiao/tmp/siibra-python/foo.py", line 26, in err
    sp.get_template().fetch(voi=bbox, resolution_mm=0.52)
  File "/home/xiao/tmp/siibra-python/siibra/volumes/volume.py", line 214, in fetch
    return self._providers[selected_format].fetch(**kwargs)
  File "/home/xiao/tmp/siibra-python/siibra/volumes/neuroglancer.py", line 102, in fetch
    result = ngvol.fetch(
  File "/home/xiao/tmp/siibra-python/siibra/volumes/neuroglancer.py", line 258, in fetch
    return scale.fetch(voi, **kwargs)
  File "/home/xiao/tmp/siibra-python/siibra/volumes/neuroglancer.py", line 444, in fetch
    chunk = self._read_chunk(gx, gy, gz, kwargs.get("channel"))
  File "/home/xiao/tmp/siibra-python/siibra/volumes/neuroglancer.py", line 398, in _read_chunk
    chunk_czyx = self.volume._io.read_chunk(self.key, (x0, x1, y0, y1, z0, z1))
  File "/home/xiao/tmp/siibra-python/venv/lib/python3.10/site-packages/neuroglancer_scripts/precomputed_io.py", line 158, in read_chunk
    buf = self.accessor.fetch_chunk(scale_key, chunk_coords)
  File "/home/xiao/tmp/siibra-python/venv/lib/python3.10/site-packages/neuroglancer_scripts/http_accessor.py", line 54, in fetch_chunk
    return self.fetch_file(chunk_url)
  File "/home/xiao/tmp/siibra-python/venv/lib/python3.10/site-packages/neuroglancer_scripts/http_accessor.py", line 74, in fetch_file
    raise DataAccessError(f"Error reading {file_url}: {exc}") from exc
neuroglancer_scripts.accessor.DataAccessError: Error reading https://neuroglancer.humanbrainproject.eu/precomputed/BigBrainRelease.2015/8bit/320um/0-64_64-128_384-357: 404 Client Error: Not Found for url: https://neuroglancer.humanbrainproject.eu/precomputed/BigBrainRelease.2015/8bit/320um/0-64_64-128_384-357
```

**Comment by AhmetNSimsek** [comment]
3d370b8c466ca6aba217cfc91466874bdb30bc08 fixes the issue
